const USStates = {
    ALABAMA: 'AL',
    ALASKA: 'AK',
    ARIZONA: 'AZ',
    ARKANSAS: 'AR',
    CALIFORNIA: 'CA',
    COLORADO: 'CO',
    CONNECTICUT: 'CT',
    DELAWARE: 'DE',
    FLORIDA: 'FL',
    GEORGIA: 'GA',
    HAWAII: 'HI',
    IDAHO: 'ID',
    ILLINOIS: 'IL',
    INDIANA: 'IN',
    IOWA: 'IA',
    KANSAS: 'KS',
    KENTUCKY: 'KY',
    LOUISIANA: 'LA',
    MAINE: 'ME',
    MARYLAND: 'MD',
    MASSACHUSETTS: 'MA',
    MICHIGAN: 'MI',
    MINNESOTA: 'MN',
    MISSISSIPPI: 'MS',
    MISSOURI: 'MO',
    MONTANA: 'MT',
    NEBRASKA: 'NE',
    NEVADA: 'NV',
    NEW_HAMPSHIRE: 'NH',
    NEW_JERSEY: 'NJ',
    NEW_MEXICO: 'NM',
    NEW_YORK: 'NY',
    NORTH_CAROLINA: 'NC',
    NORTH_DAKOTA: 'ND',
    OHIO: 'OH',
    OKLAHOMA: 'OK',
    OREGON: 'OR',
    PENNSYLVANIA: 'PA',
    RHODE_ISLAND: 'RI',
    SOUTH_CAROLINA: 'SC',
    SOUTH_DAKOTA: 'SD',
    TENNESSEE: 'TN',
    TEXAS: 'TX',
    UTAH: 'UT',
    VERMONT: 'VT',
    VIRGINIA: 'VA',
    WASHINGTON: 'WA',
    WEST_VIRGINIA: 'WV',
    WISCONSIN: 'WI',
    WYOMING: 'WY'
};

const USStatesList = [
    { text: 'Alabama', name: 'alabama', value: USStates.ALABAMA },
    { text: 'Alaska', name: 'alaska', value: USStates.ALASKA },
    { text: 'Arizona', name: 'arizona', value: USStates.ARIZONA },
    { text: 'Arkansas', name: 'arkansas', value: USStates.ARKANSAS },
    { text: 'California', name: 'california', value: USStates.CALIFORNIA },
    { text: 'Colorado', name: 'colorado', value: USStates.COLORADO },
    { text: 'Connecticut', name: 'connecticut', value: USStates.CONNECTICUT },
    { text: 'Delaware', name: 'delaware', value: USStates.DELAWARE },
    { text: 'Florida', name: 'florida', value: USStates.FLORIDA },
    { text: 'Georgia', name: 'georgia', value: USStates.GEORGIA },
    { text: 'Hawaii', name: 'hawaii', value: USStates.HAWAII },
    { text: 'Idaho', name: 'idaho', value: USStates.IDAHO },
    { text: 'Illinois', name: 'illinois', value: USStates.ILLINOIS },
    { text: 'Indiana', name: 'indiana', value: USStates.INDIANA },
    { text: 'Iowa', name: 'iowa', value: USStates.IOWA },
    { text: 'Kansas', name: 'kansas', value: USStates.KANSAS },
    { text: 'Kentucky', name: 'kentucky', value: USStates.KENTUCKY },
    { text: 'Louisiana', name: 'louisiana', value: USStates.LOUISIANA },
    { text: 'Maine', name: 'maine', value: USStates.MAINE },
    { text: 'Maryland', name: 'maryland', value: USStates.MARYLAND },
    { text: 'Massachusetts', name: 'massachusetts', value: USStates.MASSACHUSETTS },
    { text: 'Michigan', name: 'michigan', value: USStates.MICHIGAN },
    { text: 'Minnesota', name: 'minnesota', value: USStates.MINNESOTA },
    { text: 'Mississippi', name: 'mississippi', value: USStates.MISSISSIPPI },
    { text: 'Missouri', name: 'missouri', value: USStates.MISSOURI },
    { text: 'Montana', name: 'montana', value: USStates.MONTANA },
    { text: 'Nebraska', name: 'nebraska', value: USStates.NEBRASKA },
    { text: 'Nevada', name: 'nevada', value: USStates.NEVADA },
    { text: 'New Hampshire', name: 'new_hampshire', value: USStates.NEW_HAMPSHIRE },
    { text: 'New Jersey', name: 'new_jersey', value: USStates.NEW_JERSEY },
    { text: 'New Mexico', name: 'new_mexico', value: USStates.NEW_MEXICO },
    { text: 'New York', name: 'new_york', value: USStates.NEW_YORK },
    { text: 'North Carolina', name: 'north_carolina', value: USStates.NORTH_CAROLINA },
    { text: 'North Dakota', name: 'north_dakota', value: USStates.NORTH_DAKOTA },
    { text: 'Ohio', name: 'ohio', value: USStates.OHIO },
    { text: 'Oklahoma', name: 'oklahoma', value: USStates.OKLAHOMA },
    { text: 'Oregon', name: 'oregon', value: USStates.OREGON },
    { text: 'Pennsylvania', name: 'pennsylvania', value: USStates.PENNSYLVANIA },
    { text: 'Rhode Island', name: 'rhode_island', value: USStates.RHODE_ISLAND },
    { text: 'South Carolina', name: 'south_carolina', value: USStates.SOUTH_CAROLINA },
    { text: 'South Dakota', name: 'south_dakota', value: USStates.SOUTH_DAKOTA },
    { text: 'Tennessee', name: 'tennessee', value: USStates.TENNESSEE },
    { text: 'Texas', name: 'texas', value: USStates.TEXAS },
    { text: 'Utah', name: 'utah', value: USStates.UTAH },
    { text: 'Vermont', name: 'vermont', value: USStates.VERMONT },
    { text: 'Virginia', name: 'virginia', value: USStates.VIRGINIA },
    { text: 'Washington', name: 'washington', value: USStates.WASHINGTON },
    { text: 'West Virginia', name: 'west_virginia', value: USStates.WEST_VIRGINIA },
    { text: 'Wisconsin', name: 'wisconsin', value: USStates.WISCONSIN },
    { text: 'Wyoming', name: 'wyoming', value: USStates.WYOMING }
];

module.exports = {
    USStates,
    USStatesList
};